workflows:
  android-build:
    name: Android Release Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      groups:
        - android-signing
      vars:
        PACKAGE_NAME: "com.example.controledeobras"
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Build Android App Bundle (AAB)
        script: |
          gradle wrapper
          ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/bundle/release/*.aab
