name: Gerar App Bundle
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Executar Compilação
        run: |
          chmod +x gradlew
          ./gradlew bundleRelease
      - name: Baixar Arquivo
        uses: actions/upload-artifact@v4
        with:
          name: aplicativo-aab
          path: app/build/outputs/bundle/release/*.aab
